#!/usr/bin/env sh
export PATH="$HOME/bin:$PATH"
export RUNEWIDTH_EASTASIAN=0
pgrep -x sxhkd > /dev/null || sxhkd &
picom  &
mpd &
dunst &
# type speed
xset r rate 300 50 &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.config/bspwm/pacman-gruvbox.png &
launch-polybar &
bspc monitor -d  1 2 3 4 5 6 

bspc config border_width        4
bspc config window_gap          16


bspc config focused_border_color '#d5c4a1'
bspc config normal_border_color  '#3c3836'
bspc config presel_feedback_color '#ebdbb2'

bspc config split_ratio          0.50
bspc config focus_follows_pointer false
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Netease-cloud-music border=off
bspc rule -a netease-cloud-music border=off
bspc rule -a Chromium  border=off
bspc rule -a Google-chrome  border=off
bspc rule -a obs  border=off
bspc rule -a Emacs  border=off  state=floating center=true  
bspc rule -a "VirtualBox Manager" border=off



bspc rule -a Gvim  border=off
bspc rule -a Gimp-2.10  border=off
bspc rule -a firefox   border=off
bspc rule -a code-oss      border=off
bspc rule -a Code      border=off
bspc rule -a Vlc border=off state=floating center=true rectangle=820*460+0+0

bspc rule -a Electron border=off
bspc rule -a alixby3 border=off


#urxvt float
bspc rule -a URxvt:urxvt_float state=floating center=true rectangle=1400x790+0+0
bspc rule -a kitty:kitty_float state=floating center=true rectangle=1280x720+0+0

bspc rule -a KotatogramDesktop border=off state=floate  center=true rectangle=1440x810+0+0

#draw a urxvt terminal
bspc rule -a URxvt:drawing state=floating

#node calculator
bspc rule -a kitty:math state=floating center=true rectangle=1000x450+0+0
#bspc rule -a Alacritty:math state=floating center=true rectangle=1000x450+0+0
#
bspc rule -a math state=floating center=true rectangle=1000x450+0+0

bspc rule -a URxvt:math state=floating center=true rectangle=1000x450+0+0

#alacritty float
bspc rule -a alacritty_float state=floating center=true rectangle=1440x780+0+0

#draw a alacritty terminal
bspc rule -a drawing state=floating

#bspc rule -a Alacritty state=floating center=true rectangle=1280x720+0+0


#Lxappearance
bspc rule -a Lxappearance  state=floating center=true border=off rectangle=1440x810+0+0

#pcmanfm
bspc rule -a Pcmanfm border=off state=floating center=true rectangle=1440x810+0+0


#mpv
bspc rule -a mpv state=floating center=true border=off rectangle=1440x810+0+0

#simplescreenrecorder
bspc rule -a SimpleScreenRecorder state=floating center=true border=off

#telegram
bspc rule -a TelegramDesktop state=floating center=true border=off rectangle=1440x810+0+0

